# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.31.0"
    }
    # https://registry.terraform.io/providers/hashicorp/azuread/latest/docs
    azuread = {
      version = ">= 2.26.0"
    }
  }
}
